# Generated by Django 5.2.7 on 2025-10-27 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escort', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='escortsession',
            name='destination',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='escortsession',
            name='eta',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
