# Generated by Django 5.2.7 on 2025-10-27 18:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escort', '0002_escortsession_destination_escortsession_eta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='escortsession',
            name='eta',
        ),
        migrations.AlterField(
            model_name='escortsession',
            name='destination',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='escortsession',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='escortsession',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='escortsession',
            name='status',
            field=models.CharField(choices=[('Requested', 'Requested'), ('Pending', 'Pending'), ('Completed', 'Completed'), ('Panic', 'Panic')], max_length=20),
        ),
    ]
