# Generated by Django 5.2.7 on 2025-10-27 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escort', '0003_remove_escortsession_eta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='escortsession',
            name='eta',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
